---

- name: Install Zabbix repository
  shell: |
    wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
    dpkg -i zabbix-release_6.4-1+ubuntu20.04_all.deb

- name: Install Zabbix agent
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
   - zabbix-agent2 
   - zabbix-agent2-plugin-*
   
- name: Copy Zabbix conf 
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644

- name: Docker monitoring
  shell: |
    usermod -aG docker zabbix
  when: (inventory_hostname == "zbx")

- name: Add UFW rule for Zabbix agent
  tags: ufw
  community.general.ufw:
    rule: "allow"
    port: "{{item}}"
    proto: "tcp"
  with_items:
    - "10050"  

- name: Reload UFW
  tags: ufw
  community.general.ufw:
    state: "reloaded"

- name: Restart Zabbix services
  service:
    name: "zabbix-agent2"
    state: restarted
    enabled: yes