# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :ipa => {
            :box_name => "centos/8",
            :vm_name => "ipa.otus.lan", 
            :ip_addr => '192.168.57.10',
    },
    :client1 => {
            :box_name => "centos/8",
            :vm_name => "client1.otus.lan", 
            :ip_addr => '192.168.57.11',
    },
    :client2 => {
            :box_name => "centos/8",
            :vm_name => "client2.otus.lan", 
            :ip_addr => '192.168.57.12',
    },
} 
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxconfig[:vm_name]
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "2048"]
              if boxconfig[:vm_name] == "client2.otus.lan"
                    box.vm.provision "ansible" do |ansible|
                        ansible.playbook = "playbook.yml"
                        ansible.inventory_path = "staging/hosts"
                        ansible.host_key_checking = "false"
                        ansible.limit = "all"
                        ansible.tags = "base"
                    end
                end    
            end 
        end 
    end
end
