---

- name: Borg server install
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - borgbackup

- name: Create backup partition, "borg" user, add rights to backup directory
  tags: test
  shell: | 
    useradd -m borg
    mkdir /var/backup       
    chown borg:borg /var/backup
  when: (inventory_hostname == "borg")

- name: Copy preconfigure ssh private key to backup clients
  copy:
    src: "{{ item }}"
    dest: /root/.ssh
    owner: root
    group: root
    mode: 0600
  with_items:
    - id_rsa
  when: inventory_hostname in groups['backup_clients']
    
- name: Copy preconfigure ssh public key to backup server
  copy:
    src: "{{ item }}"
    dest: /tmp/id_rsa.pub
  with_items:
    - id_rsa.pub
  when: (inventory_hostname == "borg")

- name: Add preconfigure ssh public key to backup server
  tags: test1
  shell: |
    mkdir /home/borg/.ssh
    touch /home/borg/.ssh/authorized_keys
    chown -R borg: /home/borg/.ssh 
    chmod 700 ~/.ssh
    chmod 600 ~/.ssh/authorized_keys
    cat /tmp/id_rsa.pub >> /home/borg/.ssh/authorized_keys 
  when: (inventory_hostname == "borg")

- name: Copy ssh_config    
  copy:
    src: ssh_config
    dest: /root/.ssh/config 
    mode: 0400 
  
- name: Borg storage init      
  shell: |
    borg init --encryption=none borg@192.168.56.160:/var/backup/
  when: (ansible_hostname == "nginx1")

         
- name: Copy nginx backup script
  copy:
    src: nginx-backup.sh
    dest: /root/backup.sh
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "nginx1")

- name: Copy mysql backup script
  copy:
    src: mysql-backup.sh
    dest: /root/backup.sh
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "sql1")

- name: Set execution permission
  ansible.builtin.file:
    dest: /root/backup.sh
    mode: 'a+x'
  when: inventory_hostname in groups['backup_clients']
    
- name: Shedule backup job
  ansible.builtin.cron:
    name: "test"
    state: present
    minute: "0"
    hour: "*/1"
    day: "*"
    month: "*"
    weekday: "*"
    job: '/bin/sh /root/backup.sh'
  when: inventory_hostname in groups['backup_clients']
    
  

