MACHINES = {
  :inetRouter => {
        :box_name => "centos/7",
        :vm_name => "inetRouter",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "inetRouter-centralRouter"},
                   {ip: '192.168.56.10', adapter: 8},
                ]
  },
  :inetRouter2 => {
        :box_name => "centos/7",
        :vm_name => "inetRouter2",
        :net => [
                   {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "centralRouter-inetRouter2"},
                   {ip: '192.168.56.13', adapter: 8},
        ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :vm_name => "centralRouter",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "inetRouter-centralRouter"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "centralRouter-centralServer"},
                   {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "centralRouter-inetRouter2"},
                   {ip: '192.168.56.11', adapter: 8},
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :vm_name => "centralServer",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "centralRouter-centralServer"},
                   {ip: '192.168.56.12', adapter: 8},
                ]
  },

  
}
Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
      
      config.vm.define boxname do |box|
     
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxconfig[:vm_name]
  
        if boxconfig[:vm_name] == "centralServer"
         box.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook.yml"
          ansible.inventory_path = "staging/hosts"
          ansible.host_key_checking = "false"
          ansible.limit = "all"
         end
        end
  
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
          
        
  
        
      end
    end
  end