# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :master => {
            :box_name => "ubuntu/focal64",
            :vm_name => "master", 
            :ip_addr => '192.168.56.150',
    },
    :slave => {
            :box_name => "ubuntu/focal64",
            :vm_name => "slave", 
            :ip_addr => '192.168.56.151',
    },
} 
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxconfig[:vm_name]
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            if boxconfig[:vm_name] == "slave"
                box.vm.provision "ansible" do |ansible|
                    ansible.playbook = "playbook.yml"
                    ansible.inventory_path = "staging/hosts"
                    ansible.host_key_checking = "false"
                    ansible.limit = "all"
                end
            end            
        end
    end
end